apiVersion: v1
kind: Pod
metadata:
  name: advanced-pod
  labels:
    app: advanced-app
    tier: backend
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /abcd.html
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 1
      # volumeMounts:
      #   - name: nginx-config
      #     mountPath: /etc/nginx/nginx.conf
      #     subPath: nginx.conf
  # - name: redis
  #   image: redis:latest
  #   env:
  #   - name: REDIS_PASSWORD
  #     valueFrom:
  #       secretKeyRef:
  #         name: redis-password
  #         key: password
  #   ports:
  #   - containerPort: 6379
  #   volumeMounts:
  #   - name: redis-data
  #     mountPath: /data
  # volumes:
  #   - name: nginx-config
  #     configMap:
  #       name: nginx-config
  # - name: redis-data
  #   emptyDir: {}
