apiVersion: v1
kind: Pod
metadata:
  name: my-container
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
    # - name: container2
    #   image: busybox
    #   command:
    #     [
    #       "/bin/sh",
    #       "-c",
    #       "while true; do echo Hello from Container 2; sleep 10; done",
    #     ]
