apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: pod-nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
    - name: container2
      image: busybox
      command:
        [
          "/bin/sh",
          "-c",
          "while true; do echo Hello from Container 2; sleep 10; done",
        ]
