apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  # namespace: cpu-example
spec:
  containers:
    - name: cpu-demo-ctr
      image: busybox
      resources:
        limits:
          cpu: "1"
          memory: "256M"
        requests:
          cpu: "0.5"
          memory: "256M"
