apiVersion: v1
kind: Pod
metadata:
  name: pod-match-staging
  labels:
    app: my-app
    environment: staging
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
  nodeSelector:
    disk: ssd
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              # - key: app
              #   operator: In
              #   values:
              #     - my-app
              - key: environment
                operator: NotIn
                values:
                  - staging
          topologyKey: kubernetes.io/hostname
    # podAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     - labelSelector:
    #         matchExpressions:
    #           # - key: app
    #           #   operator: In
    #           #   values:
    #           #     - my-app
    #           - key: environment
    #             operator: NotIn
    #             values:
    #               - staging
    #       topologyKey: kubernetes.io/hostname
