apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - name: nginx
      port: 80
      targetPort: 80
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
