apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-busybox
spec:
  selector:
    matchLabels:
      name: my-busybox
  template:
    metadata:
      name: my-busybox
      labels:
        name: my-busybox
    spec:
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: pvc
      containers:
        - name: my-busybox
          image: busybox
          resources:
            limits:
              memory: "50Mi"
              cpu: "500m"
          command:
            - sleep
            - "600"
          volumeMounts:
            - mountPath: "/data"
              name: myvolume
