apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/test.html
          subPath: test.html
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        path: /data
        type: Directory
