apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-volume-example
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "36000"]
      volumeMounts:
        - name: ephemeral-volume
          mountPath: /test
  volumes:
    - name: ephemeral-volume
      emptyDir: {}
