apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-rsapp
  template:
    metadata:
      name: rsapp
      labels:
        app: my-rsapp
    spec:
      containers:
        - name: app
          image: nginx:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8085
